INSERT INTO PRODUCT (PRICE, CATEGORY, NAME) VALUES(100.00, 'Eletrônico', 'Celular');
INSERT INTO PRODUCT (PRICE, CATEGORY, NAME) VALUES(200.00, 'Vestuário', 'Camiseta');
INSERT INTO PRODUCT (PRICE, CATEGORY, NAME) VALUES(30.00, 'Alimentício', 'Pão');
INSERT INTO PRODUCT (PRICE, CATEGORY, NAME) VALUES(3500.00, 'Eletrodomésticos', 'Refrigerador');

